// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ThiriBankClient is the client API for ThiriBank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThiriBankClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
}

type thiriBankClient struct {
	cc grpc.ClientConnInterface
}

func NewThiriBankClient(cc grpc.ClientConnInterface) ThiriBankClient {
	return &thiriBankClient{cc}
}

func (c *thiriBankClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/pb.ThiriBank/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThiriBankServer is the server API for ThiriBank service.
// All implementations must embed UnimplementedThiriBankServer
// for forward compatibility
type ThiriBankServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	mustEmbedUnimplementedThiriBankServer()
}

// UnimplementedThiriBankServer must be embedded to have forward compatible implementations.
type UnimplementedThiriBankServer struct {
}

func (UnimplementedThiriBankServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedThiriBankServer) mustEmbedUnimplementedThiriBankServer() {}

// UnsafeThiriBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThiriBankServer will
// result in compilation errors.
type UnsafeThiriBankServer interface {
	mustEmbedUnimplementedThiriBankServer()
}

func RegisterThiriBankServer(s grpc.ServiceRegistrar, srv ThiriBankServer) {
	s.RegisterService(&ThiriBank_ServiceDesc, srv)
}

func _ThiriBank_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThiriBankServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ThiriBank/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThiriBankServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThiriBank_ServiceDesc is the grpc.ServiceDesc for ThiriBank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThiriBank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ThiriBank",
	HandlerType: (*ThiriBankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _ThiriBank_CreateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
